### ISSUE TITLE
p49页的蚂蚁行军边框问题

### ISSUE THREAD

**Issue by anlanzy** [cssmagic/CSS-Secrets#88]
想请问下，为什么p49页的animation效果，如果repeat-linear-gradient不加上background-size就无法有动画效果？

```css
@keyframes ants { to { background-position: 100% 100% } }

.borderImg6{
    margin-top: 20px;
    width: 200px;
    height: 100px;
    border: 10px solid transparent;
    background: linear-gradient(white,white) padding-box,
    repeating-linear-gradient(135deg,black 0,black 5px,transparent 0,transparent 10px)  ;
    animation: ants 12s linear infinite;
}
```

这样就没有动画效果，很迷惑？谢谢~
